language: node_js
node_js:
- 7
- 8
- 9
- 10
- 11
- 12
script: echo "Running tests against $(node -v) ...
deploy:
  provider: npm
  email: tracisnew@163.com
  api_key:
    secure: bamvOp7hMiR82AV7F4SjZ0R4hClqtYcBqIs1uSzx7onafq+70CVCdiN2aBQRnZV1wmcfNUsRo1WFJWrqabXzQmtTbyFRGWkv49aNAGuaGRzZ2owckgdy3ANfNLMtUNQz5u6qOXPB75klnjCNbgvTd9jVkxsOcbsBb+yECLdpwM1ssDLbGKwug6h+zAWDVxViMKH47A0TB+9dStF3tggv/45nkIVbZoFE045zizQd73jKaVxkOPStD3k+dNiu2+tgdlvZKJe/vuEZTt7QmOFq0whuopMF7VSosP0iCwD+H6XUdsnFov0bnRpEq1ZVoMNN71bw5J92bH3iLzJASFZ+lEfwH4uLYzB1eC3O6lMPzViDAav3FFdWlyQuvTXWFIjNZIToKWwXA2FMr15F9QH6mTRx5FCxpT/scUqzLgFagcJAiE9jTMuiU0kmxhzDqpOn93i1tq84xWjHNAfNJY2B5mNR9qYkg/l7+kdajfKOVglVS/ctezD+ia6VPmRcelc9pdSMvPF/utcY4UCvORI1w8eiGEvV/6Z7EVcWSJtGoC+lTdcCFVrFWQiDgyG92sk5UH3ClrhHKSL4JIkGuUuuvr3VZgYzop8t6lHld0fBpZyFJF8SbwKRdzAVSmLWysHwOws+Qd6yMHOnxyMWAE/jExOoY/dCiqINNwVqOEA6zjY=
  on:
    tags: true
    repo: Tracis/is-blank
